import type { Metadata } from "next";
import "./globals.css";
import Header from "@/asset/home/header";

export const metadata: Metadata = {
  title: "ChhourEchhean's PF",
  description: "Generated by EC",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          "bg-gradient-to-b from-slate-500 via-gray-100 to-gray-500 "
        }>
        <Header />
        {children}
      </body>
    </html>
  );
}
