import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "ChhourEchhean's PF",
  description: "Generated by EC",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"bg-yellow-500 h-[5000px]"}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
